# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.1password]
github = "agpenton/1password-zsh-plugin"

[plugins.f-sy-h]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.fnm]
github = "dominik-schwabe/zsh-fnm"

[plugins.eza]
github = "z-shell/zsh-eza"

[plugins.fishysave]
github = "dariogliendo/fishysave.zsh"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.async]
github = "mafredri/zsh-async"


# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
